### ISSUE TITLE
RuntimeError: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnCreate(handle)`

### ISSUE THREAD

**Issue by yuanqianguang** [JCZ404/Semi-DETR#18]
Hello, as I reimplement the model, there is a error. I don't know how to solve it. Could you give me some advices? thx

2024-01-24 21:19:05,448 - mmdet.detr_ssod - INFO - workflow: [('train', 1)], max: 120000 iters
2024-01-24 21:19:05,448 - mmdet.detr_ssod - INFO - Checkpoints will be saved to /root/autodl-tmp/Semi-DETR/work_dirs/detr_ssod_dino_detr_r50_coco_120k/1/1 by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train_detr_ssod.py", line 201, in <module>
    main()
  File "tools/train_detr_ssod.py", line 189, in main
    train_detector(
  File "/root/autodl-tmp/Semi-DETR/detr_ssod/apis/train.py", line 224, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/root/autodl-tmp/env/semi_detr/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/root/autodl-tmp/env/semi_detr/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 61, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/root/autodl-tmp/env/semi_detr/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 52, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/root/autodl-tmp/Semi-DETR/thirdparty/mmdetection/mmdet/models/detectors/base.py", line 238, in train_step
    losses = self(**data)
  File "/root/autodl-tmp/env/semi_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/env/semi_detr/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/root/autodl-tmp/Semi-DETR/thirdparty/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/root/autodl-tmp/Semi-DETR/detr_ssod/models/dino_detr_ssod.py", line 144, in forward_train
    self.foward_unsup_train(
  File "/root/autodl-tmp/Semi-DETR/detr_ssod/models/dino_detr_ssod.py", line 173, in foward_unsup_train
    return self.compute_pseudo_label_loss(student_info, teacher_info)
  File "/root/autodl-tmp/Semi-DETR/detr_ssod/models/dino_detr_ssod.py", line 177, in compute_pseudo_label_loss
    M = self._get_trans_mat(
  File "/root/autodl-tmp/env/semi_detr/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "/root/autodl-tmp/Semi-DETR/detr_ssod/models/dino_detr_ssod.py", line 811, in _get_trans_mat
    return [bt @ at.inverse() for bt, at in zip(b, a)]
  File "/root/autodl-tmp/Semi-DETR/detr_ssod/models/dino_detr_ssod.py", line 811, in <listcomp>
    return [bt @ at.inverse() for bt, at in zip(b, a)]
RuntimeError: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnCreate(handle)`
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 16209) of binary: /root/autodl-tmp/env/semi_detr/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 3/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=1
  master_addr=127.0.0.1
  master_port=29630
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_ecpui8ya/none_fw6d5udg/attempt_1/0/error.json

**Comment by JCZ404** [comment]
We have already posted the validated environment we used, you can try to check whether it can address your issue.

**Comment by johnnylecy** [comment]
> We have already posted the validated environment we used, you can try to check whether it can address your issue.

我这边也出了相同的问题，请帮忙解决一下

**Comment by JCZ404** [comment]
@johnnylecy Have you ever tried our provided conda environment? We have already validated this environment and the code can run smoothly with this conda environment on the NVIDIA A100 with CUDA12.1 without any problems.

**Comment by johnnylecy** [comment]
需要权限才能下载你们提供的环境，已经申请权限，请提供下载权限



---Original---
From: ***@***.***&gt;
Date: Thu, Aug 15, 2024 12:15 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [JCZ404/Semi-DETR] RuntimeError: cusolver error:CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnCreate(handle)` (Issue#18)




 
@johnnylecy Have you ever tried our provided conda environment? We have already validated this environment and the code can run smoothly with this conda environment on the NVIDIA A100 with CUDA12.1 without any problems.

**Comment by JCZ404** [comment]
@johnnylecy Already approved, feel free to have a try~

**Comment by johnnylecy** [comment]
> @johnnylecy Already approved, feel free to have a try~

使用了你们的虚拟环境也还是出现同样的问题

**Comment by johnnylecy** [comment]
我的机器是4090+cuda12.3

**Comment by Yuanyan266969** [comment]
> > @johnnylecy Already approved, feel free to have a try~
> 
> 使用了你们的虚拟环境也还是出现同样的问题

你好，请问你跑起来了吗

**Comment by johnnylecy** [comment]
跑不起来



---Original---
From: ***@***.***&gt;
Date: Tue, Aug 27, 2024 16:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [JCZ404/Semi-DETR] RuntimeError: cusolver error:CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnCreate(handle)` (Issue#18)




   
@johnnylecy Already approved, feel free to have a try~
  
使用了你们的虚拟环境也还是出现同样的问题
  
你好，请问你跑起来了吗

**Comment by JCZ404** [comment]
@johnnylecy You can follow the practice of @Yuanyan266969, utilize our provided conda environment, and then solve the potential problem of `AttributeError: module 'distutils' has no attribute 'version'` by referring to https://blog.csdn.net/weixin_46133643/article/details/125344874.
