### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by Raneem-MT** [JCZ404/Semi-DETR#21]
loading annotations into memory...
Traceback (most recent call last):
  File "/jmain02/home/J2AD014/mtc11/rxt49-mtc11/.conda/envs/semi/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/jmain02/home/J2AD014/mtc11/rxt49-mtc11/Semi-DETR/thirdparty/mmdetection/mmdet/datasets/custom.py", line 90, in __init__
    self.data_infos = self.load_annotations(self.ann_file)
  File "/jmain02/home/J2AD014/mtc11/rxt49-mtc11/Semi-DETR/thirdparty/mmdetection/mmdet/datasets/coco.py", line 48, in load_annotations
    self.coco = COCO(ann_file)
  File "/jmain02/home/J2AD014/mtc11/rxt49-mtc11/Semi-DETR/thirdparty/mmdetection/mmdet/datasets/api_wrappers/coco_api.py", line 23, in __init__
    super().__init__(annotation_file=annotation_file)
  File "/jmain02/home/J2AD014/mtc11/rxt49-mtc11/.local/lib/python3.8/site-packages/pycocotools/coco.py", line 81, in __init__
    with open(annotation_file, 'r') as f:
PermissionError: [Errno 13] Permission denied: '/root/paddlejob/workspace/env_run/output/temp/data/coco/annotations/semi_supervised/instances_train2017.1@10.json'

How to handle this error?

**Comment by JCZ404** [comment]
It looks like there is a problem with the target files. could you check whether the file exists in the target folder, or authorize the corresponding permission to the files(read permission)?

**Comment by Guobinyuan** [comment]
I have the same problem，
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/guobinyuan/anaconda3/envs/semidetr/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/guobinyuan/ssd/code/Semi-DETR/detr_ssod/datasets/dataset_wrappers.py", line 9, in __init__
    super().__init__([build_dataset(sup), build_dataset(unsup)], **kwargs)
  File "/home/guobinyuan/ssd/code/Semi-DETR/thirdparty/mmdetection/mmdet/datasets/builder.py", line 78, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/guobinyuan/anaconda3/envs/semidetr/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
PermissionError: CocoDataset: [Errno 13] Permission denied: '/root/paddlejob/workspace/env_run/output/temp/data/coco/annotations/semi_supervised/instances_train2017.1@10.json'
do you solve it?
