### ISSUE TITLE
NoneType when calculate unsup_loss

### ISSUE THREAD

**Issue by becauseofAI** [JCZ404/Semi-DETR#3]
```python
Traceback (most recent call last):
  File "tools/train_detr_ssod.py", line 201, in <module>
    main()
  File "tools/train_detr_ssod.py", line 189, in main
    train_detector(
  File "Semi-DETR/detr_ssod/apis/train.py", line 224, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 52, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "Semi-DETR/thirdparty/mmdetection/mmdet/models/detectors/base.py", line 238, in train_step
    losses = self(**data)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "Semi-DETR/thirdparty/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "Semi-DETR/detr_ssod/models/dino_detr_ssod.py", line 144, in forward_train
    self.foward_unsup_train(
  File "Semi-DETR/detr_ssod/models/dino_detr_ssod.py", line 173, in foward_unsup_train
    return self.compute_pseudo_label_loss(student_info, teacher_info)
  File "Semi-DETR/detr_ssod/models/dino_detr_ssod.py", line 192, in compute_pseudo_label_loss
    unsup_loss = self.unsup_loss(
  File "Semi-DETR/detr_ssod/models/dino_detr_ssod.py", line 279, in unsup_loss
    matched_row_inds, matched_col_inds = linear_sum_assignment(cost)
TypeError: 'NoneType' object is not callable
```

What's the problem? How to solve it?

Bye the way, I get the ```instances_unlabeled2017.json``` from ```http://images.cocodataset.org/annotations/image_info_unlabeled2017.zip```, and rename the name from ```image_info_unlabeled2017.json``` to ```instances_unlabeled2017.json```. But the ```instances_unlabeled2017.json``` does not have the ```categories``` field when the program is running. So I manually added it again. Is this right?

**Comment by JCZ404** [comment]
Hi, thanks for your attention on our work. For the `NoneType` error, it seems the value of `cost` becomes None, but i do not encounter this before. You can check the input and calculation of the `cls_cost`, `iou_cost`,`reg_cost` by ipdb under the single gpu running. I will also recheck our code to help you to figure out the possible reasons. For the preparation of coco unlabeled data, you are right, you can manually add the missing fields. Actually, we directly follow the data preparation practice of soft-teacher[https://github.com/microsoft/SoftTeacher]. It is recommended to follow the instruction of soft-teacher to finish the data preparation.

**Comment by SISTMrL** [comment]
@becauseofAI @JCZ404 hello, i was also encountered this problem, how to solve it? could you please give me suggestions, thanks!!!

**Comment by ilikeokoge** [comment]
@JCZ404 
Hi,
I also encountered the same error when training on the VOC dataset. Have you made any progress?

**Comment by kinvwww** [comment]
有人知道这个怎么解决了吗
