### ISSUE TITLE
KeyError: 'Sampler is not in the sampler registry' when using SemiBalanceSampler in Configuration

### ISSUE THREAD

**Issue by Wuzhongze** [JCZ404/Semi-DETR#7]
Environment:
MMCV Version: 1.3.16
MMDet Version: 2.16.0
Python Version: 3.8

Issue Details:
I am encountering an issue when trying to use a custom sampler SemiBalanceSampler in my configuration file detr_ssod_dino_detr_r50_coco_120k.py. The relevant part of the configuration is as follows:
sampler=dict(
    train=dict(
        type='SemiBalanceSampler',
        sample_ratio=[1, 4],
        by_prob=True,
        epoch_length=7330)
)

When I run the training script, I get the following error:

2023-09-05 11:48:39,111 - mmdet.detr_ssod - INFO - initialize ResNet with init_cfg {'type': 'Pretrained', 'checkpoint': 'torchvision://resnet50'}
2023-09-05 11:48:39,111 - mmcv - INFO - load model from: torchvision://resnet50
2023-09-05 11:48:39,111 - mmcv - INFO - Use load_from_torchvision loader
2023-09-05 11:48:39,192 - mmcv - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
fatal: not a git repository (or any parent up to mount point /root)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Traceback (most recent call last):
  File "tools/train_detr_ssod.py", line 201, in <module>
    main()
  File "tools/train_detr_ssod.py", line 189, in main
    train_detector(
  File "/root/autodl-tmp/Semi-DETR-main/detr_ssod/apis/train.py", line 69, in train_detector
    data_loaders = [
  File "/root/autodl-tmp/Semi-DETR-main/detr_ssod/apis/train.py", line 70, in <listcomp>
    build_dataloader(
  File "/root/autodl-tmp/Semi-DETR-main/detr_ssod/datasets/builder.py", line 68, in build_dataloader
    build_sampler(sampler_cfg, default_args=default_sampler_cfg)
  File "/root/autodl-tmp/Semi-DETR-main/detr_ssod/datasets/builder.py", line 40, in build_sampler
    return build_from_cfg(cfg, SAMPLERS, default_args)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'Sampler is not in the sampler registry'

**Comment by JCZ404** [comment]
Thanks for your attention. The issue you're encountering arises from running our code with a single GPU, which leads to the utilization of the missing 'Sampler.' To address this, it is essential to execute our code with multiple GPUs, such as using 8 GPUs as an example. This multi-GPU configuration will resolve the problem you've encountered.
